/*
 * File: app/store/FlickrStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.FlickrStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Flickr'
    ],

    config: {
        autoLoad: true,
        clearOnPageLoad: false,
        model: 'MyApp.model.Flickr',
        pageSize: 10,
        remoteFilter: true,
        storeId: 'FlickrStore',
        proxy: {
            type: 'jsonp',
            url: 'http://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=78ae61bdf2d3b52155950b1951f114d8&tags=Singapore&format=json&nojsoncallback=1',
            callbackKey: 'jsoncallback',
            reader: {
                type: 'json',
                rootProperty: 'photos.photo'
            }
        }
    }
});