/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Porticus.view.HomePanel', {
    extend: 'Ext.Panel',

    config: {
        id: 'HomePanel',
        layout: {
            animation: 'cube',
            type: 'card'
        },
        items: [
            {
                xtype: 'list',
                id: 'FlickrList',
                layout: {
                    animation: 'cube',
                    type: 'card'
                },
                itemCls: 'flickr-item',
                itemTpl: [
                    '<div class="image">',
                    '<img src="http://farm{farm}.staticflickr.com/{server}/{id}_{secret}_q.jpg">',
                    '</div>',
                    '<div class="title">',
                    '<span>{title}</span>',
                    '</div>'
                ],
                store: 'FlickrStore',
                plugins: [
                    {
                        type: 'pullrefresh'
                    },
                    {
                        autoPaging: true,
                        type: 'listpaging'
                    }
                ]
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Porticus',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'HomeBack',
                        itemId: 'mybutton',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                id: 'HomeToolbar',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'Explore',
                        itemId: 'mybutton',
                        iconCls: 'search',
                        iconMask: true,
                        text: 'Explore'
                    },
                    {
                        xtype: 'button',
                        itemId: 'Login',
                        iconCls: 'user',
                        iconMask: true,
                        text: 'Login'
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'Authenticate'
            }
        ],
        listeners: [
            {
                fn: 'onHomeBackTap',
                event: 'tap',
                delegate: '#HomeBack'
            },
            {
                fn: 'onExploreTap',
                event: 'tap',
                delegate: '#Explore'
            },
            {
                fn: 'onLoginTap',
                event: 'tap',
                delegate: '#Login'
            }
        ]
    },

    onHomeBackTap: function(button, e, options) {
        this.toggleView(true);
    },

    onExploreTap: function(button, e, options) {
        this.toggleView(true);
    },

    onLoginTap: function(button, e, options) {
        this.toggleView(false);
    },

    toggleView: function(main) {

        if(main) {
            this.down("#FlickrList").show();
            this.down("#HomeBack").hide();
            this.down("#Authenticate").hide();
        } else {
            this.down("#FlickrList").hide();
            this.down("#HomeBack").show();
            this.down("#Authenticate").show();
        }
    },

    showAuthenticateText: function() {

        var redirectUrl = Ext.Object.toQueryString({
            redirect_uri: window.location.protocol + "//" + window.location.host + window.location.pathname,
            client_id: Porticus.app.facebookAppId,
            response_type: 'token'
        });

        this
        .down("#Authenticate")
        .setHtml([
        '<div class="fbAuthenticate">',
        '<h2>Welcome to Porticus Mobile Gallery</h2>',
        '<p>This app lets you organize all your photo from different photo-sharing websites like Flickr.</p>',
        '<p>Login your Facebook account below.</p>',
        '<a class="fbLogin" href="https://m.facebook.com/dialog/oauth?' + redirectUrl + '"></a>',
        '<div class="fb-facepile" data-app-id="' + Porticus.app.facebookAppId + '" data-max-rows="2" data-width="300"></div>',
        '</div>'
        ].join(''));
    }

});