/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Porticus.view.HomePanel', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            animation: 'cube',
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Porticus',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'HomeBack',
                        itemId: 'mybutton',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                id: 'HomeToolbar',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'Explore',
                        itemId: 'mybutton',
                        iconCls: 'search',
                        iconMask: true,
                        text: 'Explore'
                    },
                    {
                        xtype: 'button',
                        itemId: 'Login',
                        iconCls: 'user',
                        iconMask: true,
                        text: 'Login'
                    }
                ]
            },
            {
                xtype: 'list',
                id: 'FlickrList',
                layout: {
                    type: 'card'
                },
                itemCls: 'flickr-item',
                itemTpl: [
                    '<div class="image">',
                    '<img src="http://farm{farm}.staticflickr.com/{server}/{id}_{secret}_q.jpg">',
                    '</div>',
                    '<div class="title">',
                    '<span>{title}</span>',
                    '</div>'
                ],
                store: 'FlickrStore',
                plugins: [
                    {
                        type: 'pullrefresh'
                    },
                    {
                        autoPaging: true,
                        type: 'listpaging'
                    }
                ]
            },
            {
                xtype: 'button',
                centered: true,
                hidden: true,
                id: 'FBLogin',
                padding: '10px 30px',
                ui: 'action',
                iconCls: 'team',
                iconMask: true,
                text: 'Login to Facebook'
            }
        ],
        listeners: [
            {
                fn: 'onHomeBackTap',
                event: 'tap',
                delegate: '#HomeBack'
            },
            {
                fn: 'onExploreTap',
                event: 'tap',
                delegate: '#Explore'
            },
            {
                fn: 'onLoginTap',
                event: 'tap',
                delegate: '#Login'
            }
        ]
    },

    onHomeBackTap: function(button, e, options) {
        this.down("#FlickrList").show();
        this.down("#HomeBack").hide();
        this.down("#FBLogin").hide();
    },

    onExploreTap: function(button, e, options) {
        this.down("#FlickrList").show();
        this.down("#HomeBack").hide();
        this.down("#FBLogin").hide();
    },

    onLoginTap: function(button, e, options) {
        this.down("#FlickrList").hide();
        this.down("#HomeBack").show();
        this.down("#FBLogin").show();
    }

});