/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.HomePanel', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            animation: 'cube',
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Porticus'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                id: 'HomeToolbar',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        iconCls: 'search',
                        iconMask: true,
                        text: 'Explore'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'user',
                        iconMask: true,
                        text: 'Login'
                    }
                ]
            },
            {
                xtype: 'list',
                id: 'FlickrList',
                layout: {
                    type: 'card'
                },
                itemCls: 'flickr-item',
                itemTpl: [
                    '<div class="image">',
                    '<img src="http://farm{farm}.staticflickr.com/{server}/{id}_{secret}_m.jpg">',
                    '</div>',
                    '<div class="title">',
                    '<span>{title}</span>',
                    '</div>'
                ],
                store: 'FlickrStore',
                plugins: [
                    {
                        type: 'pullrefresh'
                    },
                    {
                        autoPaging: true,
                        type: 'listpaging'
                    }
                ]
            }
        ]
    }

});