/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Porticus.view.MainPanel', {
    extend: 'Ext.Panel',

    config: {
        id: 'MainPanel',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Porticus'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                id: 'MainToolbar',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'HomeButton',
                        iconCls: 'home',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        id: 'PopularButton',
                        iconCls: 'star',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        id: 'CameraButton',
                        iconCls: 'bookmarks',
                        iconMask: true,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        id: 'Logout',
                        iconCls: 'user',
                        iconMask: true
                    }
                ]
            }
        ]
    },

    initialize: function() {
        console.log("asds");
    }

});